version: '3'

services:
  # PostgreSQL Service
  postgresqldb:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - dremanet
      
  # Spring Boot Uygulama Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: drema-service:latest
    depends_on:
      - postgresqldb
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=postgresqldb
    networks:
      - dremanet
      
networks:
  dremanet:
    driver: bridge
